"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def load_dotenv(path):
    """
    Read `KEY=value` lines from a .env file into the environment.

    Hand-rolled rather than pulled from a package: the file is a handful of
    database settings, and this is the whole of what is needed to read it.

    A variable already set in the real environment always wins, so running
    `DB_PASSWORD=... manage.py ...` or setting it in a container overrides the
    file rather than fighting it.
    """
    if not path.is_file():
        return

    for line in path.read_text(encoding='utf-8').splitlines():
        line = line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue

        key, _, value = line.partition('=')
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key and key not in os.environ:
            os.environ[key] = value


# backend/.env - gitignored, and the place the MySQL password belongs. Copy
# .env.example to .env and fill it in.
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-w-g#dpu34!)@ac@h$0p!_=5r(dig9a)kdbt57u6fh@(^typw-0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Hosts this server will answer to, comma separated in the environment.
#
# Django only falls back to localhost when this is empty, so reaching the dev
# server from a phone on the same Wi-Fi needs the machine's LAN address here -
# otherwise the reply is DisallowedHost. It stays a list rather than '*' so
# adding a host is a deliberate act even in development.
ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get(
        'ALLOWED_HOSTS', 'localhost,127.0.0.1,[::1]',
    ).split(',')
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'corsheaders',

    'accounts',
    'contact',
    'chat',

    'bus',
    'train',
    'plane',
    'hotel',
    'cab',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# The schema in ../schema.sql is the source of truth and is applied with the
# mysql client, not with migrations. Credentials come from the environment so
# nothing secret lands in the repo.

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('DB_NAME', 'suryabooker'),
        'USER': os.environ.get('DB_USER', 'root'),
        'PASSWORD': os.environ.get('DB_PASSWORD', ''),
        'HOST': os.environ.get('DB_HOST', '127.0.0.1'),
        'PORT': os.environ.get('DB_PORT', '3306'),
        # Hold a connection open between requests rather than reconnecting on
        # every one; MySQL's own wait_timeout closes idle ones.
        'CONN_MAX_AGE': int(os.environ.get('DB_CONN_MAX_AGE', '60')),
        'OPTIONS': {
            'charset': 'utf8mb4',
            # Strict mode makes MySQL reject out-of-range values instead of
            # silently truncating them, which keeps the CHECK constraints in
            # schema.sql meaningful.
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}


# Django REST Framework
# https://www.django-rest-framework.org/api-guide/settings/

REST_FRAMEWORK = {
    # Browsable API off: this project is consumed by the Vite front end, and
    # the HTML renderer would otherwise answer curl and fetch with a web page.
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
    ],
    # Browsing is open to anyone; booking is not. Views that require an
    # account say so with `permission_classes = [IsAuthenticated]`, which is
    # DRF's own - no booking module imports anything from `accounts`.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    # Set project-wide so every app can read a Bearer token without depending
    # on the accounts app. Absent or malformed, the request is simply
    # anonymous and only the open endpoints answer it.
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'accounts.authentication.BearerTokenAuthentication',
    ],
    # Fares are DECIMAL in MySQL; the fare summary does arithmetic on them, so
    # they have to reach the browser as JSON numbers rather than strings.
    'COERCE_DECIMAL_TO_STRING': False,
    'EXCEPTION_HANDLER': 'bus.exceptions.api_exception_handler',
    # The two open endpoints that cost something to answer are throttled:
    # the contact form sends mail, and the chat endpoint may call a paid
    # model. The scopes are read by their own views.
    'DEFAULT_THROTTLE_RATES': {
        'contact': os.environ.get('CONTACT_RATE_LIMIT', '5/hour'),
        # The chat endpoint is the other open one worth limiting: a message
        # that falls through to the model costs money. Read by
        # `chat.views.ChatThrottle`.
        'chat': os.environ.get('CHAT_RATE_LIMIT', '30/hour'),
    },
}


# Email - the contact form, and nothing else.
#
# There is no table behind the contact form: a message is validated and sent
# on, never stored. With no EMAIL_HOST set the console backend prints the mail
# to the server log, so the form works end to end in development without an
# SMTP account; fill EMAIL_HOST in .env and it goes out for real.
#
# Gmail and most providers reject a From: that is not the authenticated
# mailbox, which is why the sender is DEFAULT_FROM_EMAIL and the person who
# filled in the form is put in Reply-To instead.

EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'true').lower() == 'true'
EMAIL_TIMEOUT = int(os.environ.get('EMAIL_TIMEOUT', '10'))

EMAIL_BACKEND = (
    'django.core.mail.backends.smtp.EmailBackend' if EMAIL_HOST
    else 'django.core.mail.backends.console.EmailBackend'
)

DEFAULT_FROM_EMAIL = os.environ.get(
    'DEFAULT_FROM_EMAIL', EMAIL_HOST_USER or 'no-reply@suryabooker.in',
)

#: Where a contact form message is delivered.
CONTACT_INBOX = os.environ.get('CONTACT_INBOX', 'owner@shubhamtanks.com')


# The support assistant behind the chat bubble.
#
# Optional, and the whole app is built around that being true. With no key set
# the assistant answers from `chat/knowledge.py` alone - the scripted intents,
# the quick replies and the traveller's own bookings - which covers the common
# questions and costs nothing. Setting a key adds free-text understanding in
# any language on top; removing it again takes that away and breaks nothing.

ANTHROPIC_API_KEY = os.environ.get('ANTHROPIC_API_KEY', '')

#: Read by `chat.assistant`. Named separately from the env var so the rest of
#: the code never reaches for a raw key.
CHAT_AI_KEY = ANTHROPIC_API_KEY

CHAT_AI_MODEL = os.environ.get('CHAT_AI_MODEL', 'claude-opus-5')


# CORS - the Vite dev server runs on its own origin.
# https://github.com/adamchainz/django-cors-headers

CORS_ALLOWED_ORIGINS = [
    origin
    for origin in os.environ.get(
        'CORS_ALLOWED_ORIGINS',
        'http://localhost:5173,http://127.0.0.1:5173',
    ).split(',')
    if origin
]
